spring:
  profiles:
    active:
      - EN
      - cat
      - dev
com:
  username: YmlUserName
  password: YmlPassword
  jdbcurl: YmlUrl

---
spring:
  config:
    activate:
      on-profile: prod
com:
  username: YmlProdUserName
  password: YmlProdPassword
  jdbcurl: YmlProdUrl
